#!/usr/bin/env bash
# Bring up Hyperion for the local Curio + PoRep Market V2 stack:
#   1. Apply patches, write .env from ACTIVE/latest.json
#   2. Postgres via docker/hyperion-compose.yaml
#   3. npm ci / prisma generate+migrate / nest build
#   4. Start Nest in the background (oracle stays foreground in just up)
#
# Prerequisites:
#   - just porep-market deploy (ACTIVE / latest.json with market + FilecoinPay)
#   - Lotus RPC reachable
#   - Node.js 24.11+ / npm, docker
#
# Usage:
#   ./scripts/hyperion/up.sh
#   ./scripts/hyperion/up.sh --force
#   just hyperion up
#
# Compatible with macOS /bin/bash 3.2.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

FORCE=false
FOREGROUND=false
OUT_FILE=""

usage() {
  cat <<'EOF'
Usage: up.sh [options]

Write hyperion/.env, start Postgres + Prisma, then Nest.

Options:
  --force           Overwrite existing .env without backup
  --foreground      Run npm start in foreground (default: background)
  --out FILE        .env path (default: <HYPERION_DIR>/.env)
  -h, --help        Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=true; shift ;;
    --foreground) FOREGROUND=true; shift ;;
    --out) OUT_FILE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1 (try --help)" ;;
  esac
done

: "${HYPERION_DIR:=${REPO_ROOT}/extern/hyperion}"
COMPOSE_FILE="${REPO_ROOT}/docker/hyperion-compose.yaml"
OUT_FILE="${OUT_FILE:-${HYPERION_DIR}/.env}"
PID_FILE="${RUNTIME_ROOT}/hyperion.pid"
LOG_FILE="${RUNTIME_ROOT}/hyperion.log"

[[ -d "$HYPERION_DIR" ]] || die "hyperion submodule missing at ${HYPERION_DIR} (run: git submodule update --init --recursive)"
require_file "$COMPOSE_FILE"
require_cmd docker
require_cmd npm
require_cmd jq
require_cmd curl

hyperion_compose() {
  FCSS_HYPERION_PG_HOST_PORT="${FCSS_HYPERION_PG_HOST_PORT}" \
    docker compose -f "$COMPOSE_FILE" "$@"
}

# ---------------------------------------------------------------------------
# 1) Patches + .env
# ---------------------------------------------------------------------------

"${SCRIPT_DIR}/patch.sh"

DEPLOYMENT_JSON="$(active_latest_json 2>/dev/null || true)"
DEPLOYMENT_JSON="${DEPLOYMENT_JSON:-${POREP_MARKET_DIR}/deployments/devnet/latest.json}"
require_file "$DEPLOYMENT_JSON"

jq_addr() {
  local expr="$1"
  jq -r "$expr // empty" "$DEPLOYMENT_JSON" | tr -d '[:space:]'
}

POREP_MARKET="$(jq_addr '.contracts.PoRepMarket.proxy')"
SP_REGISTRY="$(jq_addr '.contracts.SPRegistry.proxy')"
FILECOIN_PAY="$(jq_addr '.externalDependencies.FilecoinPay')"
CHAIN_ID="$(jq -r '.chainId // .chain_id // empty' "$DEPLOYMENT_JSON" | tr -d '[:space:]')"
: "${CHAIN_ID:=31415926}"

[[ "$POREP_MARKET" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "missing PoRepMarket.proxy in ${DEPLOYMENT_JSON}"
[[ "$SP_REGISTRY" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "missing SPRegistry.proxy in ${DEPLOYMENT_JSON}"
[[ "$FILECOIN_PAY" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "missing externalDependencies.FilecoinPay in ${DEPLOYMENT_JSON}"

log "checking Lotus RPC at ${RPC_URL}"
curl -sf -m 5 -X POST "$RPC_URL" \
  -H 'Content-Type: application/json' \
  -d '{"jsonrpc":"2.0","method":"Filecoin.ChainHead","params":[],"id":1}' \
  >/dev/null || {
  runtime_dump_stack hyperion-lotus-rpc "rpc=${RPC_URL}" >/dev/null || true
  die "Lotus RPC not reachable at ${RPC_URL}"
}

DATABASE_URL="${DATABASE_URL:-${HYPERION_DATABASE_URL}}"
APP_PORT="${PORT:-${FCSS_HYPERION_APP_HOST_PORT}}"
GLIF_API_BASE_URL="${GLIF_API_BASE_URL:-${RPC_URL%/rpc/v1}/rpc}"

if [[ -e "$OUT_FILE" && "$FORCE" != true ]]; then
  backup="${OUT_FILE}.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  cp "$OUT_FILE" "$backup"
  log "backed up existing ${OUT_FILE#"$REPO_ROOT"/} -> ${backup#"$REPO_ROOT"/}"
fi

umask 077
cat >"$OUT_FILE" <<EOF
# Generated by scripts/hyperion/up.sh for local Curio + PoRep Market V2
# Source: ${DEPLOYMENT_JSON#"$REPO_ROOT"/}
# CHAIN_ID=${CHAIN_ID} RPC_URL=${RPC_URL}

NODE_ENV=development
TZ=UTC
PORT=${APP_PORT}

DATABASE_URL=${DATABASE_URL}

IP_INFO_TOKEN=

GLIF_API_BASE_URL=${GLIF_API_BASE_URL}
FILSCAN_API_BASE_URL=https://api-v2.filscan.io/api

PROMETHEUS_AUTH_TOKEN=
PROMETHEUS_METRICS_ENV=local

PO_REP_CHAIN_ID=${CHAIN_ID}
PO_REP_ARCHIVE_RPC_URL=${RPC_URL}
PO_REP_ARCHIVE_RPC_AUTH_TOKEN=
PO_REP_RECENT_RPC_URL=${RPC_URL}
PO_REP_RECENT_RPC_AUTH_TOKEN=
SP_REGISTRY_CONTRACT_ADDRESS=${SP_REGISTRY}
PO_REP_MARKET_CONTRACT_ADDRESS=${POREP_MARKET}
FILECOIN_PAY_CONTRACT_ADDRESS=${FILECOIN_PAY}
EOF

log "wrote ${OUT_FILE#"$REPO_ROOT"/}"
log "  PO_REP_MARKET=${POREP_MARKET}"
log "  SP_REGISTRY=${SP_REGISTRY}"
log "  FILECOIN_PAY=${FILECOIN_PAY}"
log "  PORT=${APP_PORT} CHAIN_ID=${CHAIN_ID}"

# ---------------------------------------------------------------------------
# 2) Postgres
# ---------------------------------------------------------------------------

runtime_ensure_dirs
log "starting Hyperion Postgres (host ${FCSS_HYPERION_PG_HOST_PORT})"
hyperion_compose up -d

log "waiting for Hyperion Postgres"
ready=false
for _ in $(seq 1 60); do
  if hyperion_compose exec -T hyperion-db pg_isready -U postgres >/dev/null 2>&1; then
    ready=true
    break
  fi
  sleep 1
done
[[ "$ready" == true ]] || {
  runtime_dump_stack hyperion-postgres >/dev/null || true
  die "hyperion-db did not become ready"
}

# ---------------------------------------------------------------------------
# 3) npm + prisma + build
# ---------------------------------------------------------------------------

cd "$HYPERION_DIR"
if [[ ! -d node_modules ]]; then
  log "npm ci"
  npm ci
fi

# typedSql (`prisma generate --sql`) introspects live tables — migrate first.
log "prisma migrate deploy"
npm run migration:deploy

log "prisma generate --sql"
npm run migration:generate

log "npm run build"
npm run build

# ---------------------------------------------------------------------------
# 4) Nest app
# ---------------------------------------------------------------------------

stop_existing() {
  if [[ -f "$PID_FILE" ]]; then
    local old
    old="$(tr -d '[:space:]' <"$PID_FILE" || true)"
    if [[ -n "$old" ]] && kill -0 "$old" 2>/dev/null; then
      log "stopping previous Hyperion pid ${old}"
      kill "$old" 2>/dev/null || true
      sleep 1
      kill -9 "$old" 2>/dev/null || true
    fi
    rm -f "$PID_FILE"
  fi
}

wait_ready() {
  # Root returns "Hyperion"; /health may fail on optional external deps.
  local url="http://${FCSS_HOST}:${APP_PORT}/"
  local ok=false
  log "waiting for Hyperion at ${url}"
  for _ in $(seq 1 90); do
    if curl -sf -m 2 "$url" >/dev/null 2>&1; then
      ok=true
      break
    fi
    sleep 1
  done
  [[ "$ok" == true ]] || {
    runtime_dump_stack hyperion-app "url=${url}" >/dev/null || true
    die "Hyperion did not become ready at ${url} (see ${LOG_FILE#"$REPO_ROOT"/})"
  }
  log "Hyperion ready — ${HYPERION_APP_URL} (docs ${HYPERION_APP_URL}/docs)"
}

if [[ "$FOREGROUND" == true ]]; then
  stop_existing
  log "npm run start:prod (foreground)"
  export PORT="$APP_PORT"
  exec npm run start:prod
fi

stop_existing
log "npm run start:prod (background → ${LOG_FILE#"$REPO_ROOT"/})"
export PORT="$APP_PORT"
(
  cd "$HYPERION_DIR"
  nohup npm run start:prod >>"$LOG_FILE" 2>&1 &
  echo $! >"$PID_FILE"
)
wait_ready
log "Hyperion pid $(tr -d '[:space:]' <"$PID_FILE")"
