#!/usr/bin/env bash
#
# Generate porep-market .env for local Curio / FEVM deploy (`just devnet_deploy`).
#
# Reads Curio docker contract bootstrap artifacts and writes the unprefixed
# FILECOIN_PAY / role vars that script/Deploy.s.sol expects, plus
# RPC_TEST / PRIVATE_KEY_TEST used by justfile's devnet_* recipes.
#
# Usage:
#   ./scripts/porep-market/gen-env.sh
#   CURIO_CONTRACTS_DIR=/path/to/contracts ./scripts/porep-market/gen-env.sh
#   ./scripts/porep-market/gen-env.sh --contracts-dir /path/to/contracts --rpc-url http://127.0.0.1:1234/rpc/v1
#
# Exit codes:
#   0  wrote .env
#   2  usage / missing dependency
#   3  missing or invalid Curio artifacts

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

# Write into the porep-market checkout by default (Deploy.s.sol / justfile live there).
cd "$POREP_MARKET_DIR"

contracts_dir="${CURIO_CONTRACTS_DIR:-$CONTRACTS_DIR}"
rpc_url="${CURIO_RPC_URL:-$RPC_URL}"
out_file="${CURIO_ENV_OUT:-.env}"
force=false

usage() {
  cat <<'EOF'
Usage: gen-env.sh [options]

Options:
  --contracts-dir DIR   Curio contracts artifact dir
                        (default: <repo>/extern/curio/docker/data/contracts or CURIO_CONTRACTS_DIR)
  --rpc-url URL         Lotus HTTP RPC for RPC_TEST
                        (default: http://127.0.0.1:1234/rpc/v1 or CURIO_RPC_URL)
  --out FILE            Output path (default: .env or CURIO_ENV_OUT)
  --force               Overwrite existing output without backup
  -h, --help            Show this help
EOF
}

# Artifact errors use exit 3 (keep prior convention).
die() {
  printf 'error: %s\n' "$*" >&2
  exit 3
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'error: required command not found: %s\n' "$1" >&2
    exit 2
  }
}

is_addr() {
  [[ "$1" =~ ^0x[0-9a-fA-F]{40}$ ]]
}

is_key() {
  [[ "$1" =~ ^0x[0-9a-fA-F]{64}$ ]]
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --contracts-dir)
      [[ $# -ge 2 ]] || { usage >&2; exit 2; }
      contracts_dir="$2"
      shift 2
      ;;
    --rpc-url)
      [[ $# -ge 2 ]] || { usage >&2; exit 2; }
      rpc_url="$2"
      shift 2
      ;;
    --out)
      [[ $# -ge 2 ]] || { usage >&2; exit 2; }
      out_file="$2"
      shift 2
      ;;
    --force)
      force=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'error: unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

need_cmd jq

addresses_file="$contracts_dir/contract_addresses.json"
key_file="$contracts_dir/deployer.private-key"
eth_file="$contracts_dir/deployer.eth-address"

[[ -d "$contracts_dir" ]] || die "Curio contracts dir not found: $contracts_dir"
[[ -f "$addresses_file" ]] || die "missing $addresses_file (is Curio contracts bootstrap done?)"
[[ -f "$key_file" ]] || die "missing $key_file"

filecoin_pay="$(jq -r '.contracts.filecoin_pay_v1 // empty' "$addresses_file")"
deployer_json="$(jq -r '.deployer.evm_address // empty' "$addresses_file")"
chain_id="$(jq -r '.chain_id // empty' "$addresses_file")"
generated_at="$(jq -r '.generated_at // empty' "$addresses_file")"

deployer="$deployer_json"
if [[ -f "$eth_file" ]]; then
  deployer_file="$(tr -d '\r\n[:space:]' < "$eth_file")"
  if [[ -n "$deployer_file" ]]; then
    if [[ -n "$deployer" && "$deployer" != "$deployer_file" ]]; then
      printf 'warning: deployer.evm_address (%s) != deployer.eth-address (%s); using eth-address file\n' \
        "$deployer" "$deployer_file" >&2
    fi
    deployer="$deployer_file"
  fi
fi

private_key="$(tr -d '\r\n[:space:]' < "$key_file")"

is_addr "$filecoin_pay" || die "invalid filecoin_pay_v1 in $addresses_file: '$filecoin_pay'"
is_addr "$deployer" || die "invalid deployer EVM address: '$deployer'"
is_key "$private_key" || die "invalid deployer private key in $key_file"

if [[ -e "$out_file" && "$force" != true ]]; then
  backup="${out_file}.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  cp "$out_file" "$backup"
  printf 'backed up existing %s -> %s\n' "$out_file" "$backup"
fi

umask 077
cat >"$out_file" <<EOF
# Generated by scripts/porep-market/gen-env.sh
# Source: $addresses_file
# generated_at=${generated_at:-unknown} chain_id=${chain_id:-unknown}
#
# Role / MetaAllocator addresses are not part of Curio bootstrap; they default
# to the Curio deployer EOA so local roles are callable with PRIVATE_KEY_TEST.

RPC_TEST=$rpc_url
PRIVATE_KEY_TEST=$private_key

# Required by script/Deploy.s.sol (unprefixed — justfile does not remap these for devnet)
FILECOIN_PAY=$filecoin_pay
TERMINATION_ORACLE=$deployer
ORACLE=$deployer
POREP_SERVICE=$deployer
OPERATOR_ADDR=$deployer
META_ALLOCATOR=$deployer

# Unused for local deploy (parity with .env.example)
RPC_CALIBNET=https://api.calibration.node.glif.io/rpc/v1
RPC_MAINNET=https://api.node.glif.io/rpc/v1
PRIVATE_KEY_CALIBNET=
PRIVATE_KEY_MAINNET=
RESCUE_PRIVATE_KEY_MAINNET=
UPGRADE_CONTRACT_NAME=Client
UPGRADE_CALLDATA=0x
EOF

printf 'wrote %s\n' "$out_file"
printf '  FILECOIN_PAY=%s\n' "$filecoin_pay"
printf '  deployer/roles=%s\n' "$deployer"
printf '  RPC_TEST=%s\n' "$rpc_url"
printf 'next: just devnet_deploy\n'
