#!/usr/bin/env bash
# Bring up compliance-data-platform for the local Curio + PoRep Market V2 stack:
#   1. Apply patches, write .env from ACTIVE/latest.json
#   2. Postgres (CDP + DMOB mock) via docker/cdp-compose.yaml
#   3. npm ci / prisma generate+migrate / nest build
#   4. Start Nest in the background (oracle stays foreground in just up)
#
# Prerequisites:
#   - just porep-market deploy (ACTIVE / latest.json with market + FilecoinPay)
#   - Lotus RPC reachable
#   - Node.js 24+, npm, docker, psql (or docker exec for seed)
#
# Usage:
#   ./scripts/cdp/up.sh
#   ./scripts/cdp/up.sh --force
#   just cdp up
#
# Compatible with macOS /bin/bash 3.2.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

FORCE=false
FOREGROUND=false
OUT_FILE=""

usage() {
  cat <<'EOF'
Usage: up.sh [options]

Write compliance-data-platform/.env, start Postgres + Prisma, then Nest.

Options:
  --force           Overwrite existing .env without backup
  --foreground      Run npm start in foreground (default: background)
  --out FILE        .env path (default: <CDP_DIR>/.env)
  -h, --help        Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=true; shift ;;
    --foreground) FOREGROUND=true; shift ;;
    --out) OUT_FILE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1 (try --help)" ;;
  esac
done

: "${CDP_DIR:=${REPO_ROOT}/extern/compliance-data-platform}"
COMPOSE_FILE="${REPO_ROOT}/docker/cdp-compose.yaml"
OUT_FILE="${OUT_FILE:-${CDP_DIR}/.env}"
PID_FILE="${RUNTIME_ROOT}/cdp.pid"
LOG_FILE="${RUNTIME_ROOT}/cdp.log"
DMOB_SEED_MARKER="${RUNTIME_ROOT}/cdp-dmob-seeded"

[[ -d "$CDP_DIR" ]] || die "cdp submodule missing at ${CDP_DIR} (run: git submodule update --init --recursive)"
require_file "$COMPOSE_FILE"
require_cmd docker
require_cmd npm
require_cmd jq
require_cmd curl

cdp_compose() {
  FCSS_CDP_PG_HOST_PORT="${FCSS_CDP_PG_HOST_PORT}" \
  FCSS_CDP_DMOB_PG_HOST_PORT="${FCSS_CDP_DMOB_PG_HOST_PORT}" \
    docker compose -f "$COMPOSE_FILE" "$@"
}

# ---------------------------------------------------------------------------
# 1) Patches + .env
# ---------------------------------------------------------------------------

"${SCRIPT_DIR}/patch.sh"

DEPLOYMENT_JSON="$(active_latest_json 2>/dev/null || true)"
DEPLOYMENT_JSON="${DEPLOYMENT_JSON:-${POREP_MARKET_DIR}/deployments/devnet/latest.json}"
require_file "$DEPLOYMENT_JSON"

jq_addr() {
  local expr="$1"
  jq -r "$expr // empty" "$DEPLOYMENT_JSON" | tr -d '[:space:]'
}

POREP_MARKET="$(jq_addr '.contracts.PoRepMarket.proxy')"
SP_REGISTRY="$(jq_addr '.contracts.SPRegistry.proxy')"
FILECOIN_PAY="$(jq_addr '.externalDependencies.FilecoinPay')"
CHAIN_ID="$(jq -r '.chainId // .chain_id // empty' "$DEPLOYMENT_JSON" | tr -d '[:space:]')"
: "${CHAIN_ID:=31415926}"

[[ "$POREP_MARKET" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "missing PoRepMarket.proxy in ${DEPLOYMENT_JSON}"
[[ "$SP_REGISTRY" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "missing SPRegistry.proxy in ${DEPLOYMENT_JSON}"
[[ "$FILECOIN_PAY" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "missing externalDependencies.FilecoinPay in ${DEPLOYMENT_JSON}"

log "checking Lotus RPC at ${RPC_URL}"
curl -sf -m 5 -X POST "$RPC_URL" \
  -H 'Content-Type: application/json' \
  -d '{"jsonrpc":"2.0","method":"Filecoin.ChainHead","params":[],"id":1}' \
  >/dev/null || {
  runtime_dump_stack cdp-lotus-rpc "rpc=${RPC_URL}" >/dev/null || true
  die "Lotus RPC not reachable at ${RPC_URL}"
}

DATABASE_URL="${DATABASE_URL:-${CDP_DATABASE_URL}}"
DMOB_DATABASE_URL="${DMOB_DATABASE_URL:-${CDP_DMOB_DATABASE_URL}}"
APP_PORT="${PORT:-${FCSS_CDP_APP_HOST_PORT}}"
GLIF_API_BASE_URL="${GLIF_API_BASE_URL:-${RPC_URL%/rpc/v1}/rpc}"

if [[ -e "$OUT_FILE" && "$FORCE" != true ]]; then
  backup="${OUT_FILE}.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  cp "$OUT_FILE" "$backup"
  log "backed up existing ${OUT_FILE#"$REPO_ROOT"/} -> ${backup#"$REPO_ROOT"/}"
fi

umask 077
cat >"$OUT_FILE" <<EOF
# Generated by scripts/cdp/up.sh for local Curio + PoRep Market V2
# Source: ${DEPLOYMENT_JSON#"$REPO_ROOT"/}
# CHAIN_ID=${CHAIN_ID} RPC_URL=${RPC_URL}

NODE_ENV=development
TZ=UTC
PORT=${APP_PORT}

DATABASE_URL=${DATABASE_URL}
DMOB_DATABASE_URL=${DMOB_DATABASE_URL}

GOOGLEAPIS_KEY=
IP_INFO_TOKEN=
GITHUB_APP_ID=
GITHUB_PRIVATE_KEY=

GLIF_API_BASE_URL=${GLIF_API_BASE_URL}
FILSCAN_API_BASE_URL=https://api-v2.filscan.io/api

CLIENT_REPORT_MAX_PROVIDER_DEAL_PERCENTAGE=25
CLIENT_REPORT_MAX_DUPLICATION_PERCENTAGE=20
CLIENT_REPORT_MAX_PERCENTAGE_FOR_LOW_REPLICA=25
CLIENT_REPORT_MAX_PERCENTAGE_FOR_REQUIRED_COPIES=34
CLIENT_REPORT_MAX_PERCENTAGE_NOT_DECLARED_PROVIDERS=30
CLIENT_REPORT_MAX_PERCENTAGE_FOR_HIGH_REPLICA=25
CLIENT_REPORT_TOTAL_UNIQ_DATA_SET_SIZE_ALLOW_EXCEEDS_PERCENTAGE=5

PROMETHEUS_AUTH_TOKEN=
PROMETHEUS_METRICS_ENV=local

ALLOCATOR_REGISTRY_REPO_OWNER=Neti-Test
ALLOCATOR_REGISTRY_REPO_NAME=filplus-allocator-governance

URL_FINDER_API_URL=

PO_REP_CHAIN_ID=${CHAIN_ID}
PO_REP_ARCHIVE_RPC_URL=${RPC_URL}
PO_REP_ARCHIVE_RPC_AUTH_TOKEN=
PO_REP_RECENT_RPC_URL=${RPC_URL}
PO_REP_RECENT_RPC_AUTH_TOKEN=
SP_REGISTRY_CONTRACT_ADDRESS=${SP_REGISTRY}
PO_REP_MARKET_CONTRACT_ADDRESS=${POREP_MARKET}
FILECOIN_PAY_CONTRACT_ADDRESS=${FILECOIN_PAY}
EOF

log "wrote ${OUT_FILE#"$REPO_ROOT"/}"
log "  PO_REP_MARKET=${POREP_MARKET}"
log "  SP_REGISTRY=${SP_REGISTRY}"
log "  FILECOIN_PAY=${FILECOIN_PAY}"
log "  PORT=${APP_PORT} CHAIN_ID=${CHAIN_ID}"

# ---------------------------------------------------------------------------
# 2) Postgres + DMOB seed
# ---------------------------------------------------------------------------

runtime_ensure_dirs
log "starting CDP Postgres (host ${FCSS_CDP_PG_HOST_PORT}) + DMOB mock (${FCSS_CDP_DMOB_PG_HOST_PORT})"
cdp_compose up -d

log "waiting for CDP Postgres"
ready=false
for _ in $(seq 1 60); do
  if cdp_compose exec -T cdp-db pg_isready -U postgres >/dev/null 2>&1; then
    ready=true
    break
  fi
  sleep 1
done
[[ "$ready" == true ]] || {
  runtime_dump_stack cdp-postgres >/dev/null || true
  die "cdp-db did not become ready"
}

log "waiting for DMOB Postgres"
ready=false
for _ in $(seq 1 60); do
  if cdp_compose exec -T cdp-dmob-db pg_isready -U postgres >/dev/null 2>&1; then
    ready=true
    break
  fi
  sleep 1
done
[[ "$ready" == true ]] || {
  runtime_dump_stack cdp-dmob-postgres >/dev/null || true
  die "cdp-dmob-db did not become ready"
}

if [[ ! -f "$DMOB_SEED_MARKER" ]]; then
  log "seeding DMOB mock from ci/dmob-mock-db.sql (first run)"
  require_file "${CDP_DIR}/ci/dmob-mock-db.sql"
  # pageinspect is optional in the dump; ignore extension errors on slim images.
  set +e
  cdp_compose exec -T cdp-dmob-db psql -U postgres -d postgres \
    <"${CDP_DIR}/ci/dmob-mock-db.sql" >/tmp/fcss-cdp-dmob-seed.log 2>&1
  seed_rc=$?
  set -e
  if [[ "$seed_rc" -ne 0 ]]; then
    # Re-try after creating a no-op pageinspect stub if extension missing.
    if grep -qi 'pageinspect' /tmp/fcss-cdp-dmob-seed.log; then
      log "dmob seed hit pageinspect; retrying with extension skipped via ON_ERROR_STOP=0"
      cdp_compose exec -T cdp-dmob-db \
        psql -U postgres -d postgres -v ON_ERROR_STOP=0 \
        <"${CDP_DIR}/ci/dmob-mock-db.sql" >/tmp/fcss-cdp-dmob-seed.log 2>&1 \
        || die "DMOB mock seed failed (see /tmp/fcss-cdp-dmob-seed.log)"
    else
      die "DMOB mock seed failed (see /tmp/fcss-cdp-dmob-seed.log)"
    fi
  fi
  touch "$DMOB_SEED_MARKER"
  log "DMOB mock seeded"
else
  log "DMOB mock already seeded (${DMOB_SEED_MARKER#"$REPO_ROOT"/})"
fi

# ---------------------------------------------------------------------------
# 3) npm + prisma + build
# ---------------------------------------------------------------------------

cd "$CDP_DIR"
if [[ ! -d node_modules ]]; then
  log "npm ci"
  npm ci
fi

# typedSql (`prisma generate --sql`) introspects live tables — migrate first.
log "prisma migrate deploy"
npm run migration:deploy

log "prisma generate --sql (cdp + dmob)"
npm run migration:generate
npm run migration:generate_dmob

log "npm run build"
npm run build

# ---------------------------------------------------------------------------
# 4) Nest app
# ---------------------------------------------------------------------------

stop_existing() {
  if [[ -f "$PID_FILE" ]]; then
    local old
    old="$(tr -d '[:space:]' <"$PID_FILE" || true)"
    if [[ -n "$old" ]] && kill -0 "$old" 2>/dev/null; then
      log "stopping previous CDP pid ${old}"
      kill "$old" 2>/dev/null || true
      sleep 1
      kill -9 "$old" 2>/dev/null || true
    fi
    rm -f "$PID_FILE"
  fi
}

wait_ready() {
  local url="http://${FCSS_HOST}:${APP_PORT}/version"
  local ok=false
  log "waiting for CDP at ${url}"
  for _ in $(seq 1 90); do
    if curl -sf -m 2 "$url" >/dev/null 2>&1; then
      ok=true
      break
    fi
    sleep 1
  done
  [[ "$ok" == true ]] || {
    runtime_dump_stack cdp-app "url=${url}" >/dev/null || true
    die "CDP did not become ready at ${url} (see ${LOG_FILE#"$REPO_ROOT"/})"
  }
  log "CDP ready — ${CDP_APP_URL} (docs ${CDP_APP_URL}/docs)"
}

if [[ "$FOREGROUND" == true ]]; then
  stop_existing
  log "npm run start:prod (foreground)"
  export PORT="$APP_PORT"
  exec npm run start:prod
fi

stop_existing
log "npm run start:prod (background → ${LOG_FILE#"$REPO_ROOT"/})"
export PORT="$APP_PORT"
(
  cd "$CDP_DIR"
  nohup npm run start:prod >>"$LOG_FILE" 2>&1 &
  echo $! >"$PID_FILE"
)
wait_ready
log "CDP pid $(tr -d '[:space:]' <"$PID_FILE")"
